name: Prueba de tokens

on:
  push:

jobs:
  comprobar-tokens:
    runs-on: self-hosted

    steps:
      - name: Comprobar token DEV
        shell: powershell
        run: |
          if ("${{ secrets.DEV_TOKEN }}" -eq $env:LOCAL_DEV_TOKEN) {
            Write-Host "Los tokens coinciden"
          } else {
            Write-Error "Los tokens NO coinciden"
            exit 1
          }
