name: Prueba de tokens

on:
  push:

jobs:
  comprobar-tokens:
    runs-on: self-hosted

    steps:
      - name: Comprobar token DEV
        shell: powershell
        run: |
          Write-Host "La variable LOCAL_DEV_TOKEN existe: $([bool]$env:LOCAL_DEV_TOKEN)"
          Write-Host "Longitud de LOCAL_DEV_TOKEN: $($env:LOCAL_DEV_TOKEN.Length)"
          Write-Host "Longitud de DEV_TOKEN: $("${{ secrets.DEV_TOKEN }}".Length)"
